language: python

matrix:
    include:
        - python: "2.7"
          os: linux
          dist: xenial
          env: TOXENV=py27
        - python: "pypy"
          os: linux
          dist: trusty  # pypy download on xenial is 403
          env: TOXENV=pypy
        - python: "3.4"
          os: linux
          dist: xenial
          env: TOXENV=py34
        - python: "3.5"
          os: linux
          dist: xenial
          env: TOXENV=py35
        - python: "3.6"
          os: linux
          dist: xenial
          env: TOXENV=py36
        - python: "3.7"
          os: linux
          dist: xenial
          env: TOXENV=py37

install: pip install tox

script: tox
